// src/components/admin/BlogPostEditor.tsx
import React, { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { X, Save } from 'lucide-react';

interface BlogPostEditorProps {
  blogPost?: any;
  onClose: () => void;
  onSaved: (post: any) => void;
}

interface MangaTitle {
  id: string;
  title: string;
}

const BlogPostEditor: React.FC<BlogPostEditorProps> = ({ blogPost, onClose, onSaved }) => {
  const isEditing = Boolean(blogPost);
  const [formData, setFormData] = useState({
    title: blogPost?.title || '',
    slug: blogPost?.slug || '',
    manga_id: blogPost?.manga_id || '',
    featured_image: blogPost?.featured_image || '',
    seo_description: blogPost?.seo_description || '',
    seo_keywords: blogPost?.seo_keywords || '',
    content: blogPost?.content || '',
    published_date: blogPost?.published_date ? new Date(blogPost.published_date).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16),
  });
  const [mangaList, setMangaList] = useState<MangaTitle[]>([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchMangaList = async () => {
      const { data, error } = await supabase.from('manga_entries').select('id, title').order('title');
      if (!error) setMangaList(data || []);
    };
    fetchMangaList();
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const generateSlug = () => {
    setFormData((prev) => ({ ...prev, slug: prev.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    try {
      const postData = {
        ...formData,
        manga_id: formData.manga_id || null,
        featured_image: formData.featured_image || null,
        published_date: formData.published_date ? new Date(formData.published_date).toISOString() : null,
      };
      let result;
      if (isEditing) {
        const { data, error } = await supabase
          .from('blog_posts')
          .update(postData)
          .eq('id', blogPost.id)
          .select()
          .single();
        if (error) throw error;
        result = data;
      } else {
        const { data, error } = await supabase
          .from('blog_posts')
          .insert(postData)
          .select()
          .single();
        if (error) throw error;
        result = data;
      }
      onSaved(result);
      onClose();
    } catch (err: any) {
      setError(err?.message || 'Failed to save blog post.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 9999,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.8)'
    }}>
      <div style={{
        backgroundColor: '#111',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        borderRadius: '0.5rem',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        width: '100%',
        maxWidth: '800px',
        maxHeight: '90vh',
        overflowY: 'auto',
        padding: '1.5rem',
        position: 'relative'
      }}>
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold manga-title">{isEditing ? 'Edit Blog Post' : 'Add New Blog Post'}</h2>
          <button type="button" onClick={onClose} className="p-2 hover:text-red-500 transition-colors" aria-label="Close">
            <X className="w-6 h-6" />
          </button>
        </div>

        {error && (
          <div className="bg-red-900/30 border border-red-500 p-4 mb-6 flex items-start">
            <span className="w-5 h-5 text-red-500 mr-2 mt-0.5 flex-shrink-0"><X /></span>
            <div>
              <p className="font-bold text-red-500">Error</p>
              <p className="text-sm">{error}</p>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Left column */}
            <div className="space-y-6">
              {/* Title */}
              <div>
                <label htmlFor="title" className="block text-sm font-medium mb-2">Title <span className="text-red-500">*</span></label>
                <input
                  id="title"
                  name="title"
                  type="text"
                  value={formData.title}
                  onChange={handleChange}
                  required
                  placeholder="Blog post title"
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none transition-colors"
                />
              </div>
              {/* Slug */}
              <div>
                <label htmlFor="slug" className="block text-sm font-medium mb-2">Slug <span className="text-xs text-gray-500">(URL-friendly)</span></label>
                <div className="flex gap-2">
                  <span className="inline-flex items-center px-3 rounded-l border border-r-0 border-white/20 bg-gray-800 text-gray-300 text-sm">/blog/</span>
                  <input
                    id="slug"
                    name="slug"
                    type="text"
                    value={formData.slug}
                    onChange={handleChange}
                    required
                    className="flex-1 px-3 py-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none rounded-r"
                    placeholder="my-blog-post-title"
                  />
                </div>
                <button 
                  type="button" 
                  onClick={generateSlug} 
                  className="mt-1 text-sm text-blue-400 hover:text-blue-300"
                >
                  Generate from title
                </button>
              </div>
              {/* Associated Manga */}
              <div>
                <label htmlFor="manga_id" className="block text-sm font-medium mb-2">Associated Manga <span className="text-xs text-gray-500">(Optional)</span></label>
                <select
                  id="manga_id"
                  name="manga_id"
                  value={formData.manga_id || ''}
                  onChange={handleChange}
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none transition-colors"
                >
                  <option value="">None (General Blog Post)</option>
                  {mangaList.map((manga) => (
                    <option key={manga.id} value={manga.id}>{manga.title}</option>
                  ))}
                </select>
              </div>
              {/* Featured Image */}
              <div>
                <label htmlFor="featured_image" className="block text-sm font-medium mb-2">Featured Image URL <span className="text-xs text-gray-500">(Optional)</span></label>
                <input
                  id="featured_image"
                  name="featured_image"
                  type="url"
                  value={formData.featured_image}
                  onChange={handleChange}
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-blue-500 focus:outline-none transition-colors"
                  placeholder="https://example.com/image.jpg"
                />
                {formData.featured_image && (
                  <img src={formData.featured_image} alt="Featured preview" className="h-32 w-auto object-cover rounded mt-2" />
                )}
              </div>
            </div>
            {/* Right column */}
            <div className="space-y-6">
              {/* SEO Description */}
              <div>
                <label htmlFor="seo_description" className="block text-sm font-medium mb-2">SEO Description <span className="text-xs text-gray-500">(150-160 chars)</span></label>
                <textarea
                  id="seo_description"
                  name="seo_description"
                  value={formData.seo_description}
                  onChange={handleChange}
                  rows={2}
                  required
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none transition-colors"
                  placeholder="SEO description"
                />
              </div>
              {/* SEO Keywords */}
              <div>
                <label htmlFor="seo_keywords" className="block text-sm font-medium mb-2">SEO Keywords <span className="text-xs text-gray-500">(Comma-separated)</span></label>
                <input
                  id="seo_keywords"
                  name="seo_keywords"
                  type="text"
                  value={formData.seo_keywords}
                  onChange={handleChange}
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none transition-colors"
                  placeholder="manga, manhwa, action, fantasy, etc."
                />
              </div>

              {/* Publish Date */}
              <div>
                <label htmlFor="published_date" className="block text-sm font-medium mb-2">Publish Date</label>
                <input
                  id="published_date"
                  name="published_date"
                  type="datetime-local"
                  value={formData.published_date}
                  onChange={handleChange}
                  className="w-full p-2 bg-black/30 border border-white/20 focus:border-blue-500 focus:outline-none transition-colors"
                />
              </div>
            </div>
          </div>

          {/* Content */}
          <div>
            <label htmlFor="content" className="block text-sm font-medium mb-2">Content <span className="text-red-500">*</span></label>
            <textarea
              id="content"
              name="content"
              value={formData.content}
              onChange={handleChange}
              rows={10}
              required
              className="w-full p-2 bg-black/30 border border-white/20 focus:border-red-500 focus:outline-none transition-colors"
              placeholder="Write your blog post content here. HTML formatting is supported."
            />
            <div className="text-xs text-gray-400 mt-1">HTML formatting is supported.</div>
          </div>

          {/* Action buttons */}
          <div className="flex justify-end gap-4 mt-6 border-t border-white/10 pt-6">
            <button
              type="button"
              onClick={onClose}
              className="manga-border px-4 py-2 hover:text-red-500 transition-colors flex items-center gap-2"
              disabled={saving}
            >
              <X className="w-5 h-5" /> Cancel
            </button>
            <button
              type="submit"
              className="bg-red-500/20 hover:bg-red-500/30 manga-border px-4 py-2 flex items-center gap-2 transition-all"
              disabled={saving || !formData.title || !formData.content}
            >
              <Save className="w-5 h-5" /> {saving ? 'Saving...' : isEditing ? 'Update Post' : 'Create Post'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default BlogPostEditor;

// src/components/admin/BlogPostEditor.vue
<template>
  <div class="blog-post-editor">
    <div class="mb-6 flex items-center justify-between">
      <h2 class="text-2xl font-bold">{{ isEditing ? 'Edit Blog Post' : 'Add New Blog Post' }}</h2>
      <button 
        @click="$emit('close')" 
        class="text-gray-500 hover:text-gray-700"
      >
        <span class="sr-only">Close</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <form @submit.prevent="saveBlogPost" class="space-y-6">
      <!-- Title -->
      <div>
        <label for="title" class="block text-sm font-medium text-gray-700">Title</label>
        <input 
          type="text" 
          id="title" 
          v-model="formData.title" 
          required
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          placeholder="Enter blog post title"
        />
      </div>

      <!-- Slug -->
      <div>
        <label for="slug" class="block text-sm font-medium text-gray-700">
          Slug
          <span class="ml-1 text-gray-500 text-xs">(URL-friendly version of title)</span>
        </label>
        <div class="mt-1 flex rounded-md shadow-sm">
          <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
            /blog/
          </span>
          <input 
            type="text" 
            id="slug" 
            v-model="formData.slug" 
            required
            class="flex-1 block w-full px-3 py-2 border border-gray-300 rounded-none rounded-r-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            placeholder="my-blog-post-title"
          />
        </div>
        <button 
          type="button" 
          @click="generateSlug" 
          class="mt-1 text-sm text-indigo-600 hover:text-indigo-500"
        >
          Generate from title
        </button>
      </div>

      <!-- Associated Manga (Optional) -->
      <div>
        <label for="manga" class="block text-sm font-medium text-gray-700">
          Associated Manga 
          <span class="ml-1 text-gray-500 text-xs">(Optional)</span>
        </label>
        <select 
          id="manga" 
          v-model="formData.manga_id" 
          class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
        >
          <option value="">None (General Blog Post)</option>
          <option v-for="manga in mangaList" :key="manga.id" :value="manga.id">
            {{ manga.title }}
          </option>
        </select>
      </div>

      <!-- Featured Image URL -->
      <div>
        <label for="featured_image" class="block text-sm font-medium text-gray-700">
          Featured Image URL
          <span class="ml-1 text-gray-500 text-xs">(Optional)</span>
        </label>
        <input 
          type="url" 
          id="featured_image" 
          v-model="formData.featured_image" 
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          placeholder="https://example.com/image.jpg"
        />
        <div v-if="formData.featured_image" class="mt-2">
          <img :src="formData.featured_image" alt="Featured image preview" class="h-32 w-auto object-cover rounded-md shadow-sm" />
        </div>
      </div>

      <!-- SEO Description -->
      <div>
        <label for="seo_description" class="block text-sm font-medium text-gray-700">
          SEO Description
          <span class="ml-1 text-gray-500 text-xs">(150-160 characters recommended)</span>
        </label>
        <textarea 
          id="seo_description" 
          v-model="formData.seo_description" 
          rows="2"
          required
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          placeholder="Brief description of the blog post for search engines and social sharing"
        ></textarea>
        <div class="mt-1 text-xs text-gray-500">
          {{ formData.seo_description.length }} / 160 characters
        </div>
      </div>

      <!-- SEO Keywords -->
      <div>
        <label for="seo_keywords" class="block text-sm font-medium text-gray-700">
          SEO Keywords
          <span class="ml-1 text-gray-500 text-xs">(Comma-separated)</span>
        </label>
        <input 
          type="text" 
          id="seo_keywords" 
          v-model="formData.seo_keywords" 
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          placeholder="manga, manhwa, action, fantasy, etc."
        />
      </div>

      <!-- Content (Rich Text Editor) -->
      <div>
        <label for="content" class="block text-sm font-medium text-gray-700">Content</label>
        <textarea 
          id="content" 
          v-model="formData.content" 
          rows="15"
          required
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          placeholder="Write your blog post content here. HTML formatting is supported."
        ></textarea>
        <div class="mt-1 text-xs text-gray-500">
          HTML formatting is supported.
        </div>
      </div>

      <!-- Publish Date -->
      <div>
        <label for="published_date" class="block text-sm font-medium text-gray-700">Publish Date</label>
        <input 
          type="datetime-local" 
          id="published_date" 
          v-model="formData.published_date" 
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <!-- Actions -->
      <div class="flex justify-end space-x-3 pt-5">
        <button 
          type="button" 
          @click="$emit('close')" 
          class="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Cancel
        </button>
        <button 
          type="submit" 
          class="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          :disabled="saving"
        >
          {{ saving ? 'Saving...' : (isEditing ? 'Update Post' : 'Create Post') }}
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import { ref, reactive, computed, onMounted } from 'vue';
import { supabase } from '../../lib/supabaseClient';

export default {
  name: 'BlogPostEditor',
  
  props: {
    blogPost: {
      type: Object,
      default: null
    }
  },
  
  emits: ['close', 'saved'],
  
  setup(props, { emit }) {
    const saving = ref(false);
    const mangaList = ref([]);
    
    // Determine if we're editing or creating
    const isEditing = computed(() => !!props.blogPost);
    
    // Form data with defaults
    const formData = reactive({
      title: '',
      slug: '',
      manga_id: '',
      featured_image: '',
      seo_description: '',
      seo_keywords: '',
      content: '',
      published_date: new Date().toISOString().slice(0, 16), // Format for datetime-local input
      views: 0
    });
    
    // If editing, populate form with existing data
    const initializeForm = () => {
      if (isEditing.value) {
        const post = props.blogPost;
        formData.title = post.title;
        formData.slug = post.slug;
        formData.manga_id = post.manga_id || '';
        formData.featured_image = post.featured_image || '';
        formData.seo_description = post.seo_description || '';
        formData.seo_keywords = post.seo_keywords || '';
        formData.content = post.content;
        
        // Format the date for the input
        if (post.published_date) {
          const date = new Date(post.published_date);
          formData.published_date = date.toISOString().slice(0, 16);
        }
        
        formData.views = post.views || 0;
      }
    };
    
    // Generate slug from title
    const generateSlug = () => {
      if (!formData.title) return;
      
      // Convert to lowercase, replace spaces with hyphens, remove special chars
      const slug = formData.title
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^\w-]+/g, '')
        .replace(/--+/g, '-')
        .replace(/^-+|-+$/g, '');
        
      formData.slug = slug;
    };
    
    // Get list of manga for the select dropdown
    const fetchMangaList = async () => {
      try {
        const { data, error } = await supabase
          .from('manga_entries')
          .select('id, title')
          .order('title');
          
        if (error) throw error;
        mangaList.value = data || [];
      } catch (error) {
        console.error('Error fetching manga list:', error);
      }
    };
    
    // Save the blog post
    const saveBlogPost = async () => {
      try {
        saving.value = true;
        
        // Format the data for saving
        const postData = {
          title: formData.title,
          slug: formData.slug,
          manga_id: formData.manga_id || null,
          featured_image: formData.featured_image || null,
          seo_description: formData.seo_description,
          seo_keywords: formData.seo_keywords || null,
          content: formData.content,
          published_date: new Date(formData.published_date).toISOString(),
          views: formData.views
        };
        
        // For existing posts, include the updated_at timestamp
        if (isEditing.value) {
          postData.updated_at = new Date().toISOString();
        }
        
        let result;
        
        if (isEditing.value) {
          // Update existing post
          const { data, error } = await supabase
            .from('blog_posts')
            .update(postData)
            .eq('id', props.blogPost.id)
            .select()
            .single();
            
          if (error) throw error;
          result = data;
        } else {
          // Create new post
          const { data, error } = await supabase
            .from('blog_posts')
            .insert(postData)
            .select()
            .single();
            
          if (error) throw error;
          result = data;
        }
        
        emit('saved', result);
        emit('close');
      } catch (error) {
        console.error('Error saving blog post:', error);
        alert('An error occurred while saving the blog post. Please try again.');
      } finally {
        saving.value = false;
      }
    };
    
    // Initialize
    onMounted(() => {
      fetchMangaList();
      initializeForm();
    });
    
    return {
      formData,
      mangaList,
      isEditing,
      saving,
      generateSlug,
      saveBlogPost
    };
  }
}
</script>
